/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.xndrive.first_try

fun main(args: Array<String>) {
    println(App().greeting)
    App().showSomeAmazingWords()
}

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
    var sebuahSapaanYangRamah: String = "Selamat Pagi"

    fun showSomeAmazingWords() {
        print("Hello Kotlin")
        println("Mari belajar Kotlin bersama")
        print(sebuahSapaanYangRamah+" dan "+"Tetap semangat jangan menyerah.")
    }
}
